version: "3"
networks:
  bri:
    driver: bridge
services:
  mysql:
    image: "mysql:5.7"
    container_name: "mysql"
    restart: always
    ports:
      - 33066:3306
    environment:
      - MYSQL_ROOT_PASSWORD=1qaz2wsx
      - TZ=Asia/Tokyo
    volumes:
      - /home/centos/mysql_data:/var/lib/mysql
      - /home/centos/opt/docker_deploy/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - bri
  auction_spider:
    image: 'auction_spider:1.2'
    container_name: "auction_spider"
    restart: always
    tty: true
    ports:
      - '8888:8888'
    volumes:
      - '/home/centos/project/spider:/spider'
    environment:
      - TZ=Asia/Tokyo
    networks:
      - bri
  splash:
    image: scrapinghub/splash
    container_name: "splash"
    restart: always
    ports:
      - '8050:8050'
    environment:
      - TZ=Asia/Tokyo
    networks:
      - bri
  manage-web:
    image: nginx:latest
    container_name: manage-web
    restart: always
    privileged: true
    ports:
      - '8855:80'
    volumes:
      - ../front/nginx/conf.d:/etc/nginx/conf.d
      - ../front/manage-web/dist:/manage-web/dist
    environment:
      - LANG=C.UTF-8
      - TZ=Asia/Tokyo
    networks:
      - bri
