version: "3"
networks:
  bri:
    driver: bridge
services:
  mysql:
    image: "mysql:5.7"
    container_name: "mysql"
    restart: always
    ports:
      - 33066:3306
    environment:
      - MYSQL_ROOT_PASSWORD=1qaz2wsx
      - TZ=Asia/Tokyo
    volumes:
      - /home/centos/mysql_data:/var/lib/mysql
      - /home/centos/opt/crawl_deploy/mysql/my.cnf:/etc/mysql/mysql.conf.d/my.cnf
    networks:
      - bri
  auction_spider:
    image: 'auction_spider:1.2'
    container_name: "auction_spider"
    restart: always
    tty: true
    ports:
      - '8889:6800'
    volumes:
      - '/home/centos/project/spider:/spider'
    environment:
      - TZ=Asia/Tokyo
    networks:
      - bri
  greenmethyl-scrapyd:
    image: 'auction_spider:2.0'
    container_name: "greenmethyl-scrapyd"
    restart: always
    tty: true
    ports:
      - '8889:6800'
    volumes:
      - '../back/scrapyd/scrapyd.conf:/etc/scrapyd/scrapyd.conf'
      - '../back/scrapyd/scrapyd_run:/scrapyd_run'
    environment:
      - TZ=Asia/Tokyo
#    command: [ "cd","/scrapyd_run","&&","scrapyd",">","./scrapyd.log","&" ]
    command:
      - sh
      - -c
      - |
        cd /scrapyd_run
        scrapyd
    networks:
      - bri
  splash:
    image: scrapinghub/splash
    container_name: "splash"
    restart: always
    ports:
      - '8050:8050'
    environment:
      - TZ=Asia/Tokyo
    networks:
      - bri
  manage-web:
    image: nginx:latest
    container_name: manage-web
    restart: always
    privileged: true
    ports:
      - '8890:80'
    volumes:
      - ../front/nginx/conf.d:/etc/nginx/conf.d
      - ../front/manage-web/dist:/manage-web/dist
    environment:
      - LANG=C.UTF-8
      - TZ=Asia/Tokyo
    networks:
      - bri
  data_manage:
    image: openjdk:1.8
    container_name: data_manage
    hostname: data_manage
    environment:
      - TZ=Asia/Tokyo
    restart: always
    volumes:
      - ../back/data_manage/crawl-all-0.1.0-exec.jar:/app.jar
      - ../back/scrapyd/scrapyd_run/logs:/scrapyd/scrapyd_run/logs
    ports:
      - '8891:8080'
    command: [ "java","-Djava.net.preferIPv4Stack=true","-jar","/app.jar","--spring.profiles.active=db_test, core, admin_test" ]
    networks:
      - bri
