version: "3"
networks:
  bri:
    driver: bridge
services:
  mysql:
    image: "mysql:5.7"
    container_name: "mysql"
    restart: always
    ports:
      - 33066:3306
    environment:
      - MYSQL_ROOT_PASSWORD=1qaz2wsx
      - TZ=Asia/Tokyo
    volumes:
      - /home/centos/mysql_data:/var/lib/mysql
      - /home/centos/opt/crawl_deploy/mysql/my.cnf:/etc/mysql/mysql.conf.d/my.cnf
    networks:
      - bri
  greenmethyl-scrapyd:
    image: 'scrapyd:latest'
    container_name: "greenmethyl-scrapyd"
    restart: always
    tty: true
    ports:
      - '8889:6800'
    volumes:
      - ../back/scrapyd/logs:/logs
      - ../back/scrapyd/dbs:/dbs
    environment:
      - TZ=Asia/Tokyo
    networks:
      - bri
  manage-web:
    image: nginx:latest
    container_name: manage-web
    restart: always
    privileged: true
    ports:
      - '443:443'
    volumes:
      - ../front/nginx/conf.d:/etc/nginx/conf.d
      - ../front/manage-web/dist:/manage-web/dist
      - ../front/nginx/ssl/demo.xmengya.com.key:/etc/nginx/demo.xmengya.com.key
      - ../front/nginx/ssl/demo.xmengya.com_bundle.crt:/etc/nginx/demo.xmengya.com_bundle.crt
    environment:
      - LANG=C.UTF-8
      - TZ=Asia/Tokyo
    networks:
      - bri
  data_manage:
    image: openjdk:1.8
    container_name: data_manage
    hostname: data_manage
#    deploy:
#      resources:
#        limits:
#          cpus: '0.2'
#          memory: 700M
    environment:
      - TZ=Asia/Tokyo
      - SERVER_PORT=8080
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DB=crawl_auction
      - MYSQL_USER=crawl
      - MYSQL_PASSWORD=methyl@2022
      - SCRAPYD_HOST=http://greenmethyl-scrapyd
      - SCRAPYD_PORT=6800
#      - SCRAPYD_LOG_HOST=http://54.250.151.61
#      - SCRAPYD_LOG_PORT=8891
      - SCRAPYD_LOG_HOST=
      - SCRAPYD_LOG_PORT=
      - SCRAPYD_PROJECT_NAME=greenmethyl-spider
      - SCRAPYD_MAXJOB_COUNT=5
      - SCRAPYD_LOG_PATH=/back/scrapyd/logs
      - EMAIL_SMTP_HOST=smtp.gmail.com
      - EMAIL_SMTP_PORT=587
      - EMAIL_SMTP_USER=jamesneo0614@gmail.com
      - EMAIL_SMTP_PASSWORD=xgdanpuzjfdwticp
      - THREAD_COUNT=300
    restart: always
    volumes:
      - ../back/data_manage/crawl-all-0.1.0-exec.jar:/app.jar
      - ../back/data_manage/logs:/logs
      - ../back/scrapyd/logs:/back/scrapyd/logs
    ports:
      - '8891:8080'
    command: [ "java","-Djava.net.preferIPv4Stack=true","-jar","/app.jar","--spring.profiles.active=db_aws, core, admin_aws" ]
    networks:
      - bri
